// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gae-backend-analysis/api/controller"
	"gae-backend-analysis/bootstrap"
	"gae-backend-analysis/consume"
	"gae-backend-analysis/cron"
	"gae-backend-analysis/executor"
	"gae-backend-analysis/internal/tokenutil"
	"gae-backend-analysis/repository"
	"gae-backend-analysis/task"
	"gae-backend-analysis/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp init application.
func InitializeApp() (*bootstrap.Application, error) {
	env := bootstrap.NewEnv()
	databases := bootstrap.NewDatabases(env)
	poolsFactory := bootstrap.NewPoolFactory()
	channels := bootstrap.NewChannel()
	controllers := bootstrap.NewControllers()
	generationRepository := repository.NewGenerationRepository(databases)
	connection := bootstrap.NewRabbitConnection(env)
	messageHandler := consume.NewMessageHandler(connection)
	generateEvent := consume.NewGenerateEvent(messageHandler, env, channels, generationRepository)
	generationCron := cron.NewGenerationCron(generationRepository, channels, env, generateEvent)
	cronExecutor := executor.NewCronExecutor(generationCron)
	consumeExecutor := executor.NewConsumeExecutor(generateEvent)
	client := bootstrap.NewRedisDatabase(env)
	dataExecutor := executor.NewDataExecutor(client)
	bootstrapExecutor := bootstrap.NewExecutors(cronExecutor, consumeExecutor, dataExecutor)
	application := &bootstrap.Application{
		Env:          env,
		Databases:    databases,
		PoolsFactory: poolsFactory,
		Channels:     channels,
		Controllers:  controllers,
		Executor:     bootstrapExecutor,
	}
	return application, nil
}

// wire.go:

var appSet = wire.NewSet(bootstrap.NewEnv, tokenutil.NewTokenUtil, bootstrap.NewDatabases, bootstrap.NewRedisDatabase, bootstrap.NewMysqlDatabase, bootstrap.NewMongoDatabase, bootstrap.NewPoolFactory, bootstrap.NewChannel, bootstrap.NewRabbitConnection, bootstrap.NewControllers, bootstrap.NewExecutors, repository.NewGenerationRepository, repository.NewChatRepository, repository.NewBotRepository, consume.NewStorageEvent, consume.NewGenerateEvent, consume.NewMessageHandler, cron.NewGenerationCron, executor.NewCronExecutor, executor.NewConsumeExecutor, executor.NewDataExecutor, usecase.NewChatUseCase, task.NewAskChatTask, task.NewChatTitleTask, task.NewConvertTask, controller.NewTestController, wire.Struct(new(bootstrap.Application), "*"))
