file_worker = "" 
file_project = ""
info_project = {
    'repo_id': '仓库ID',
    'owner_name': '拥有者名称',
    'owner_id': '拥有者ID',
    'name': '名称',
    'created_at': '创建时间',
    'updated_at': '更新时间',
    'forks_count': 'Forks数量',
    'network_count': '网络数量',
    'open_issues_count': '开放问题数量',
    'stargazers_count': '星标数量',
    'subscribers_count': '订阅者数量',
    'watchers_count': '观看者数量',
    'contributors_id': '贡献者ID',
    'main_language':'主要语言',
    'languages': '语言'
}

info_worker = {
    'login': '登录名',
    'id': 'ID',
    'avatar_url': '头像 URL',
    'url': '网址',
    'html_url': 'HTML 网址',
    'gravatar_id': 'Gravatar ID',
    'name': '姓名',
    'company': '公司',
    'blog': '博客',
    'location': '位置',
    'email': '邮箱',
    'bio': '个人简介',
    'public_repos': '公开仓库数量',
    'public_gists': '公开 Gist 数量',
    'follower_count': '粉丝数量',
    'following_count': '关注数量',
    'created_at': '创建时间',
    'updated_at': '更新时间',
    'type': '类型',
    'followers': '粉丝列表',
    'followings': '关注列表'
}
languages_dict = {
    'ActionScript': ['Flash 动画与应用开发', 'Web 动态内容'],
    'Arc': ['函数式编程', '高阶编程', '学术研究'],
    'C': ['操作系统开发', '嵌入式系统', '高性能应用', '硬件编程'],
    'C#': ['游戏开发', 'Windows 应用开发', '企业级应用开发', 'Web 应用开发'],
    'C++': ['游戏开发', '系统软件开发', '高性能计算', '实时系统', '嵌入式系统', '大型软件开发'],
    'CSS': ['Web 样式设计', '前端开发'],
    'Common Lisp': ['人工智能', '符号计算', '学术研究'],
    'Emacs Lisp': ['Emacs 配置与扩展', '自动化脚本'],
    'Erlang': ['高并发系统', '分布式系统', '实时系统', '电信行业'],
    'Forth': ['嵌入式系统', '硬件编程', '实时操作系统'],
    'HTML': ['Web 页面结构', '前端开发'],
    'Io': ['简洁、动态语言', '学术研究', '嵌入式系统'],
    'Java': ['企业级应用', 'Android 开发', '大型系统与后台服务', '分布式系统', '大数据与 Hadoop'],
    'JavaScript': ['前端 Web 开发', '后端开发', '跨平台移动应用开发', 'Web 动态交互与动画'],
    'Jupyter Notebook': ['数据分析', '机器学习', '数据可视化', '科学计算'],
    'LilyPond': ['音乐符号编排', '音乐创作与排版'],
    'Lua': ['嵌入式脚本语言', '游戏开发', '脚本扩展与自动化'],
    'Nu': ['函数式编程', '命令行工具开发'],
    'OCaml': ['函数式编程', '编译器开发', '学术研究'],
    'Objective-C': ['iOS 和 macOS 应用开发'],
    'PHP': ['Web 开发', '动态网页生成', '服务器端脚本'],
    'Parrot': ['编译器设计', '动态语言运行时环境'],
    'Perl': ['文本处理', '正则表达式', '系统管理', '网络编程', 'Web 开发'],
    'PostScript': ['打印与图形输出', '图形编程', '电子出版'],
    'Python': ['数据科学与机器学习', 'Web 开发', '自动化脚本', '科学计算与数值分析', '人工智能与机器人', '网络编程'],
    'Ruby': ['Web 开发', '快速原型开发', '自动化脚本'],
    'Scheme': ['函数式编程', '教学与学术研究', '编译器设计'],
    'Shell': ['系统管理与自动化', '批量文件处理', '命令行工具和脚本'],
    'TeX': ['学术排版', '技术文档', '数学公式排版'],
    'Vim Script': ['Vim 编辑器的插件与配置', '自动化脚本'],
    'XSLT': ['XML 文档转换', 'Web 开发', '数据格式转换'],
    'Ada': ['嵌入式系统', '实时系统', '航空航天应用', '高可靠性系统'],
    'ALGOL': ['算法研究', '学术研究', '编译器设计'],
    'Bash': ['系统脚本编写', '自动化', '系统管理'],
    'Bliss': ['系统编程', '编译器开发'],
    'Clojure': ['函数式编程', '并发系统', 'Web 开发'],
    'COBOL': ['企业级应用', '银行与金融系统'],
    'Crystal': ['高性能应用', 'Web 开发'],
    'D': ['系统编程', '高性能计算'],
    'Delphi': ['桌面应用开发', 'Windows 应用开发'],
    'F#': ['函数式编程', '金融建模', '科学计算与分析'],
    'Fortran': ['科学计算', '数值分析', '高性能计算'],
    'Go': ['网络服务与 Web 服务', '云计算与微服务', '系统编程与命令行工具开发'],
    'Hack': ['Web 开发', 'PHP 的增强版'],
    'Haskell': ['函数式编程', '并发系统', '学术研究'],
    'HyperTalk': ['HyperCard 应用开发'],
    'IDL': ['科学计算', '数据分析', '图像处理'],
    'Io': ['简洁的面向对象语言', '学术研究', '嵌入式系统'],
    'J': ['数学与科学计算', '数据分析'],
    'LabVIEW': ['自动化与测试', '硬件控制', '工程应用'],
    'Lisp': ['人工智能', '符号计算', '学术研究'],
    'Matlab': ['科学计算', '数据分析与建模', '信号处理'],
    'Nim': ['系统编程', '游戏开发', '嵌入式系统'],
    'OCaml': ['函数式编程', '编译器开发', '学术研究'],
    'Pascal': ['教学与学术研究', '系统编程'],
    'Perl': ['文本处理', '正则表达式', '系统管理', '网络编程', 'Web 开发'],
    'PostScript': ['图形编程', '打印与图形输出'],
    'Prolog': ['人工智能', '逻辑编程', '推理系统'],
    'R': ['数据科学', '统计分析', '机器学习', '数据可视化'],
    'Ruby': ['Web 开发', '快速原型开发', '自动化脚本'],
    'Scala': ['大数据处理', '分布式系统', '后端服务开发'],
    'Smalltalk': ['面向对象编程', '图形界面开发', '学术研究'],
    'Tcl': ['GUI 开发', '自动化与脚本语言', '嵌入式系统'],
    'VHDL': ['硬件设计与开发', 'FPGA 编程'],
    'Verilog': ['硬件设计与开发', 'FPGA 编程'],
    'Zig': ['系统编程', '高性能应用']
}
countries = [
    "Argentina", "Australia", "Austria", "Azerbaijan", "Bahamas", "Pakistan",
    "Belarus", "Belgium", "Botswana", "Brazil", "Brunei", "Bulgaria",
    "Canada", "Chile", "China", "Colombia", "Croatia", "Cyprus",
    "Czech Republic", "Denmark", "Egypt", "Estonia", "Ethiopia", "Finland",
    "France", "Germany", "Greece", "Jamaica", "Japan", "Jordan", "Kazakhstan",
    "South Korea", "Kuwait", "Latvia", "Lebanon", "Lithuania", "Luxembourg",
    "Malaysia", "Maldives", "Mexico", "Monaco", "Mongolia", "Morocco",
    "Netherlands", "New Zealand", "Nigeria", "Norway", "Pakistan", "Philippines",
    "Poland", "Portugal", "Qatar", "Romania", "Russia", "Singapore",
    "Slovakia", "Slovenia", "South Africa", "Spain", "Sweden", "Switzerland",
    "Taiwan", "Thailand", "Turkey", "Ukraine", "United Arab Emirates", "United Kingdom",
    "United States", "Uzbekistan", "Vietnam"
]
worker_use_list = ['公开仓库数量', '公开 Gist 数量', '粉丝数量', '关注数量']
project_use_list = ['Forks数量','网络数量','开放问题数量','星标数量','订阅者数量','观看者数量']