# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnation.proto\x12\x06nation\"!\n\rNationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"8\n\x0eNationResponse\x12&\n\nNationInfo\x18\x01 \x03(\x0b\x32\x12.nation.NationInfo\"2\n\nNationInfo\x12\x0e\n\x06Nation\x18\x01 \x01(\t\x12\x14\n\x0cNationWeight\x18\x02 \x01(\x03\x32M\n\rNationService\x12<\n\x0bQueryNation\x12\x15.nation.NationRequest\x1a\x16.nation.NationResponseB\tZ\x07.proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.proto/'
  _globals['_NATIONREQUEST']._serialized_start=24
  _globals['_NATIONREQUEST']._serialized_end=57
  _globals['_NATIONRESPONSE']._serialized_start=59
  _globals['_NATIONRESPONSE']._serialized_end=115
  _globals['_NATIONINFO']._serialized_start=117
  _globals['_NATIONINFO']._serialized_end=167
  _globals['_NATIONSERVICE']._serialized_start=169
  _globals['_NATIONSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
