# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relation_net.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'relation_net.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12relation_net.proto\x12\x08relation\"#\n\x0fRelationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"6\n\x10RelationResponse\x12\"\n\x07netInfo\x18\x01 \x03(\x0b\x32\x11.relation.NetInfo\"\x97\x01\n\x07NetInfo\x12\x10\n\x08relation\x18\x01 \x01(\t\x12\x11\n\tusername1\x18\x02 \x01(\t\x12\x11\n\tusername2\x18\x03 \x01(\t\x12)\n\x0bnationInfo1\x18\x04 \x01(\x0b\x32\x14.relation.NationInfo\x12)\n\x0bnationInfo2\x18\x05 \x01(\x0b\x32\x14.relation.NationInfo\"2\n\nNationInfo\x12\x0e\n\x06Nation\x18\x01 \x01(\t\x12\x14\n\x0cNationWeight\x18\x02 \x01(\x03\x32_\n\x12RelationNetService\x12I\n\x10QueryRelationNet\x12\x19.relation.RelationRequest\x1a\x1a.relation.RelationResponseB\tZ\x07.proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relation_net_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.proto/'
  _globals['_RELATIONREQUEST']._serialized_start=32
  _globals['_RELATIONREQUEST']._serialized_end=67
  _globals['_RELATIONRESPONSE']._serialized_start=69
  _globals['_RELATIONRESPONSE']._serialized_end=123
  _globals['_NETINFO']._serialized_start=126
  _globals['_NETINFO']._serialized_end=277
  _globals['_NATIONINFO']._serialized_start=279
  _globals['_NATIONINFO']._serialized_end=329
  _globals['_RELATIONNETSERVICE']._serialized_start=331
  _globals['_RELATIONNETSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
