// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: relation_net.proto

package __proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelationNetService_QueryRelationNet_FullMethodName = "/relation.RelationNetService/QueryRelationNet"
)

// RelationNetServiceClient is the client API for RelationNetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelationNetServiceClient interface {
	QueryRelationNet(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*RelationResponse, error)
}

type relationNetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationNetServiceClient(cc grpc.ClientConnInterface) RelationNetServiceClient {
	return &relationNetServiceClient{cc}
}

func (c *relationNetServiceClient) QueryRelationNet(ctx context.Context, in *RelationRequest, opts ...grpc.CallOption) (*RelationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelationResponse)
	err := c.cc.Invoke(ctx, RelationNetService_QueryRelationNet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationNetServiceServer is the server API for RelationNetService service.
// All implementations must embed UnimplementedRelationNetServiceServer
// for forward compatibility.
type RelationNetServiceServer interface {
	QueryRelationNet(context.Context, *RelationRequest) (*RelationResponse, error)
	mustEmbedUnimplementedRelationNetServiceServer()
}

// UnimplementedRelationNetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelationNetServiceServer struct{}

func (UnimplementedRelationNetServiceServer) QueryRelationNet(context.Context, *RelationRequest) (*RelationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryRelationNet not implemented")
}
func (UnimplementedRelationNetServiceServer) mustEmbedUnimplementedRelationNetServiceServer() {}
func (UnimplementedRelationNetServiceServer) testEmbeddedByValue()                            {}

// UnsafeRelationNetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelationNetServiceServer will
// result in compilation errors.
type UnsafeRelationNetServiceServer interface {
	mustEmbedUnimplementedRelationNetServiceServer()
}

func RegisterRelationNetServiceServer(s grpc.ServiceRegistrar, srv RelationNetServiceServer) {
	// If the following call pancis, it indicates UnimplementedRelationNetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelationNetService_ServiceDesc, srv)
}

func _RelationNetService_QueryRelationNet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationNetServiceServer).QueryRelationNet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationNetService_QueryRelationNet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationNetServiceServer).QueryRelationNet(ctx, req.(*RelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelationNetService_ServiceDesc is the grpc.ServiceDesc for RelationNetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelationNetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relation.RelationNetService",
	HandlerType: (*RelationNetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryRelationNet",
			Handler:    _RelationNetService_QueryRelationNet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relation_net.proto",
}
