// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: nation.proto

package __proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *NationRequest) Reset() {
	*x = NationRequest{}
	mi := &file_nation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NationRequest) ProtoMessage() {}

func (x *NationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NationRequest.ProtoReflect.Descriptor instead.
func (*NationRequest) Descriptor() ([]byte, []int) {
	return file_nation_proto_rawDescGZIP(), []int{0}
}

func (x *NationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type NationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NationInfo []*NationInfo `protobuf:"bytes,1,rep,name=NationInfo,proto3" json:"NationInfo,omitempty"`
}

func (x *NationResponse) Reset() {
	*x = NationResponse{}
	mi := &file_nation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NationResponse) ProtoMessage() {}

func (x *NationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NationResponse.ProtoReflect.Descriptor instead.
func (*NationResponse) Descriptor() ([]byte, []int) {
	return file_nation_proto_rawDescGZIP(), []int{1}
}

func (x *NationResponse) GetNationInfo() []*NationInfo {
	if x != nil {
		return x.NationInfo
	}
	return nil
}

type NationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nation       string `protobuf:"bytes,1,opt,name=Nation,proto3" json:"Nation,omitempty"`
	NationWeight int64  `protobuf:"varint,2,opt,name=NationWeight,proto3" json:"NationWeight,omitempty"`
}

func (x *NationInfo) Reset() {
	*x = NationInfo{}
	mi := &file_nation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NationInfo) ProtoMessage() {}

func (x *NationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NationInfo.ProtoReflect.Descriptor instead.
func (*NationInfo) Descriptor() ([]byte, []int) {
	return file_nation_proto_rawDescGZIP(), []int{2}
}

func (x *NationInfo) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *NationInfo) GetNationWeight() int64 {
	if x != nil {
		return x.NationWeight
	}
	return 0
}

var File_nation_proto protoreflect.FileDescriptor

var file_nation_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x0d, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0e, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x4e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x48, 0x0a, 0x0a, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x0a, 0x0c, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x32, 0x4d, 0x0a, 0x0d, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x15, 0x2e, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nation_proto_rawDescOnce sync.Once
	file_nation_proto_rawDescData = file_nation_proto_rawDesc
)

func file_nation_proto_rawDescGZIP() []byte {
	file_nation_proto_rawDescOnce.Do(func() {
		file_nation_proto_rawDescData = protoimpl.X.CompressGZIP(file_nation_proto_rawDescData)
	})
	return file_nation_proto_rawDescData
}

var file_nation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nation_proto_goTypes = []any{
	(*NationRequest)(nil),  // 0: nation.NationRequest
	(*NationResponse)(nil), // 1: nation.NationResponse
	(*NationInfo)(nil),     // 2: nation.NationInfo
}
var file_nation_proto_depIdxs = []int32{
	2, // 0: nation.NationResponse.NationInfo:type_name -> nation.NationInfo
	0, // 1: nation.NationService.QueryNation:input_type -> nation.NationRequest
	1, // 2: nation.NationService.QueryNation:output_type -> nation.NationResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nation_proto_init() }
func file_nation_proto_init() {
	if File_nation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nation_proto_goTypes,
		DependencyIndexes: file_nation_proto_depIdxs,
		MessageInfos:      file_nation_proto_msgTypes,
	}.Build()
	File_nation_proto = out.File
	file_nation_proto_rawDesc = nil
	file_nation_proto_goTypes = nil
	file_nation_proto_depIdxs = nil
}
